// 供 Broker 互相通信以及验证客户端时使用
KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="user"
    password="password"
    user_user="password";
};

// 供 Broker 作为客户端连接其他 Broker 时使用
KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="user"
    password="password";
};